services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - node_modules:/app/src/node_modules
      - ./tmp:/tmp
    working_dir: /app/src
    command: sh -c "pnpm install && pnpm dev"

volumes:
  node_modules: {}
